pdf("alignmentscore.pdf") 
scores <- read.table('./data/merged/all.merged.scores',h=T)
hist(rep(scores$score, scores$count), breaks=100, xlab="alignment score", main="alignement scores")
abline(v=200, col='red')
dev.off()
